"""eliminar columna pais de usuer

Revision ID: fc2e3f8d0e8c
Revises: 8e1fe4146f05
Create Date: 2022-05-25 20:18:42.565118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2e3f8d0e8c'
down_revision = '8e1fe4146f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
